// Generates runtime schemas for every wire type from the TypeScript that ts-rs already emits,
// so Rust stays the one source of truth and a schema cannot drift from its type.
//
// ts-to-zod reads one file at a time and turns a cross-file import into `z.any()`, so the
// generated types are first flattened into one input file, which is deleted afterwards.
import { execFileSync } from "node:child_process";
import { readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const GENERATED = new URL("../src/generated/", import.meta.url).pathname;
const INPUT = join(GENERATED, "wire.ts");
const OUTPUT = join(GENERATED, "schemas.ts");
const SKIP = new Set(["index.ts", "wire.ts", "schemas.ts"]);

const declarations = readdirSync(GENERATED)
  .filter((name) => name.endsWith(".ts") && !SKIP.has(name))
  .sort()
  .flatMap((name) => readFileSync(join(GENERATED, name), "utf8").split("\n").filter((line) => line.trim() && !line.startsWith("import ") && !line.startsWith("//")));

writeFileSync(INPUT, `${declarations.join("\n")}\n`);
try {
  execFileSync("npx", ["ts-to-zod", "src/generated/wire.ts", "src/generated/schemas.ts"], { stdio: "inherit" });
  const schemas = readFileSync(OUTPUT, "utf8")
    .replace('// Generated by ts-to-zod', "// GENERATED from the ts-rs types by scripts/gen-schemas.mjs. DO NOT EDIT.\n// Run: pnpm gen:schemas")
    .replaceAll('from "./flat"', 'from "./index"')
    .replaceAll('from "./wire"', 'from "./index"');
  writeFileSync(OUTPUT, schemas);
  console.log(`wrote ${OUTPUT}`);
} finally {
  rmSync(INPUT, { force: true });
}
